src/apps/api/urls.py
from django.urls import path, include
from rest_framework import routers

from apps.api.views import (
    TestEndpointApiView, LoginApiView, LogoutApiView, RestoreSessionApiView
)
from apps.api.viewsets import SubscriptionViewSet, TopicViewSet

router = routers.DefaultRouter()
router.register('subscriptions', SubscriptionViewSet, base_name='subscriptions')
router.register('topics', TopicViewSet, base_name='topics')

app_name = 'api'

urlpatterns = [

    path('', include(router.urls)),
    path('login/', LoginApiView.as_view(), name='login'),
    path('logout/', LogoutApiView.as_view(), name='logout'),
    path('restore/session', RestoreSessionApiView.as_view(), name='restore-session'),
    path('test/endpoint/', TestEndpointApiView.as_view(), name='test-endpoint'),

]

src/apps/auth/urls.py
from django.urls import path

from apps.auth.views import SignUpView, ActivateAccountView

urlpatterns = [
    path('register/', SignUpView.as_view(), name='signup'),
    path('activate/<str:uidb64>/<str:token>/',
        ActivateAccountView.as_view(), name='activate'),
]

src/apps/notifications/urls.py
from django.urls import path

from apps.notifications.views import (
    TopicListView, TopicUpdateView, TopicCreateView,
    SubscriptionListView, SubscriptionUpdateView, SubscriptionCreateView,
    SubscriptionRemoveView, SubscriptionConfirmView
)

app_name = 'notifications'

urlpatterns = [
    path('topics/', TopicListView.as_view(), name='topic-list'),
    path('topics/add/', TopicCreateView.as_view(), name='topic-add'),
    path('topics/<int:pk>/', TopicUpdateView.as_view(), name='topic-update'),
    path('subscriptions/', SubscriptionListView.as_view(),
         name='subscription-list'),
    path('subscriptions/add/', SubscriptionCreateView.as_view(),
         name='subscription-add'),
    path('subscriptions/<int:pk>/', SubscriptionUpdateView.as_view(),
         name='subscription-update'),
    path('subscriptions/remove/<int:pk>/', SubscriptionRemoveView.as_view(),
         name='subscription-remove'),
    path('subscriptions/confirm/<str:uid>/<str:token>/', SubscriptionConfirmView.as_view(),
         name='subscription-confirm'),
]

src/apps/users/urls.py
from django.urls import path

from apps.users.views import (
    SignUpView, SignInView, ActivateAccountView,
    IndexView
)
app_name = 'users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signin/', SignInView.as_view(), name='signin'),
    path('activate/<str:uidb64>/<str:token>/',
        ActivateAccountView.as_view(), name='activate'),
    path('', IndexView.as_view(), name='index')
]

src/conf/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls', namespace='users')),
    path('notifications/', include('apps.notifications.urls', namespace='notifications')),
    path('api/', include('apps.api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/apps/auth_core/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import UserCreationForm

from apps.auth_core.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False,
                                 help_text=_('Optional.'), label=_('First name'))
    last_name = forms.CharField(max_length=30, required=False,
                                help_text=_('Optional.'), label=_('Last name'))
    email = forms.EmailField(max_length=254, help_text=_(
        'Required. Inform a valid email address.'), label=_('Email address'))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1',
                  'password2',)

src/apps/notifications/forms.py
from django import forms

from apps.notifications.models import Subscription, Topic


class SubscriptionUpdateForm(forms.ModelForm):

    class Meta:
        model = Subscription
        fields = ['topic', 'protocol', 'endpoint']

    def __init__(self, *args, **kwargs):
        self.current_user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['topic'].widget.attrs['class'] = 'custom-select'
        self.fields['protocol'].widget.attrs['class'] = 'custom-select'
        self.fields['endpoint'].widget.attrs['class'] = 'form-control'
        self.fields['topic'].queryset = Topic.objects.filter(
            owner_id=self.current_user.id)

src/apps/users/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import UserCreationForm

from apps.users.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False,
                                 help_text=_('Optional.'), label=_('First name'))
    last_name = forms.CharField(max_length=30, required=False,
                                help_text=_('Optional.'), label=_('Last name'))
    email = forms.EmailField(max_length=254, help_text=_(
        'Required. Inform a valid email address.'), label=_('Email address'))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1',
                  'password2',)

src/apps/api/views.py
import logging

from django.contrib.auth import login, logout
from django.shortcuts import render
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.api.serializers import LoginSerializer, RestoreSessionSerializer

logger = logging.getLogger(__file__)


class TestEndpointApiView(APIView):
    def post(self, request):
        logger.debug(request.data)
        return Response()


class LoginApiView(APIView):
    def post(self, request):
        data = request.data
        serializer = LoginSerializer(data=data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        login(request, user)
        return Response({'status': 'Login successful'})


class LogoutApiView(APIView):

    permission_classes = (IsAuthenticated, )

    def get(self, request):
        logout(request)
        return Response(status=status.HTTP_204_NO_CONTENT)


class RestoreSessionApiView(APIView):

    def get(self, request):
        if request.user.is_authenticated:
            serialized_data = RestoreSessionSerializer(self.request.user).data
            serialized_data['is_authenticated'] = True
        else:
            serialized_data = RestoreSessionSerializer().data
            serialized_data['is_authenticated'] = False
        return Response(serialized_data)

src/apps/auth_core/views.py
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.views.generic import FormView
from django.views import View
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from django.urls import reverse_lazy

from apps.auth_core.tokens import account_activation_token
from apps.auth_core.forms import SignUpForm
from apps.auth_core.models import User


class SignUpView(SuccessMessageMixin, FormView):

    form_class = SignUpForm
    template_name = 'auth/registration.html'
    success_url = reverse_lazy('success')
    success_message = 'Used created successfully'

    def send_activation_email(self, user):
        current_site = get_current_site(self.request)
        subject = 'Activate Your MySite Account'
        message = render_to_string('auth/account_activation_email.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': force_text(urlsafe_base64_encode(force_bytes(user.pk))),
            'token': account_activation_token.make_token(user),
        })
        user.email_user(subject, message)

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        self.send_activation_email(user)
        return super().form_valid(form)


class ActivateAccountView(View):

    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user,
                                                                     token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('signup')
        else:
            return render(request, 'auth/base.html')

src/apps/notifications/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.utils.translation import ugettext_lazy as _
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib import messages

from apps.notifications.models import Topic, Subscription
from apps.notifications.forms import SubscriptionUpdateForm
from apps.notifications.tokens import subscription_activation_token


class TopicListView(LoginRequiredMixin, ListView):
    model = Topic
    template_name = 'dashboard/topic_list.html'
    context_object_name = 'topics'
    paginate_by = 10

    def get_queryset(self):
        return self.request.user.topics.all().order_by('title')


class TopicUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Topic
    template_name = 'dashboard/topic_update.html'
    fields = ['title']
    success_url = reverse_lazy('notifications:topic-list')
    success_message = _('Topic updated successfully.')

    def get_queryset(self):
        return self.request.user.topics.all()


class TopicCreateView(LoginRequiredMixin, CreateView):
    model = Topic
    template_name = 'dashboard/topic_create.html'
    fields = ['title']
    success_url = reverse_lazy('notifications:topic-list')
    success_message = _('Topic created successfully.')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()
        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(self.get_success_url())


class SubscriptionListView(LoginRequiredMixin, ListView):
    model = Subscription
    template_name = 'dashboard/subscription_list.html'
    context_object_name = 'subscriptions'
    paginate_by = 10

    def get_queryset(self):
        return Subscription.objects.filter(
            topic__owner=self.request.user).order_by('topic')


class SubscriptionUpdateView(SuccessMessageMixin, LoginRequiredMixin,
                             UpdateView):
    model = Subscription
    template_name = 'dashboard/subscription_update.html'
    success_url = reverse_lazy('notifications:subscription-list')
    success_message = _('Subscription updated successfully.')
    form_class = SubscriptionUpdateForm

    def get_queryset(self):
        return Subscription.objects.filter(topic__owner=self.request.user)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class SubscriptionCreateView(SuccessMessageMixin, LoginRequiredMixin,
                             CreateView):
    model = Subscription
    template_name = 'dashboard/subscription_create.html'
    form_class = SubscriptionUpdateForm
    success_url = reverse_lazy('notifications:subscription-list')
    success_message = _('Subscription created successfully.')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class SubscriptionRemoveView(LoginRequiredMixin, DeleteView):
    model = Subscription
    template_name = 'dashboard/subscription_delete.html'
    success_url = reverse_lazy('notifications:subscription-list')
    success_message = _('Subscription deleted successfully.')

    def get_queryset(self):
        return Subscription.objects.filter(topic__owner=self.request.user)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super().delete(request, *args, **kwargs)


class SubscriptionConfirmView(View):

    redirect_url = reverse_lazy('users:index')

    def post(self, uid, token):
        try:
            id = force_text(urlsafe_base64_decode(uid))
            subscription = Subscription.objects.get(pk=id)
        except (
        TypeError, ValueError, OverflowError, Subscription.DoesNotExist):
            subscription = None

        if subscription is not None and subscription_activation_token.check_token(
                subscription,
                token):
            subscription.status = Subscription.STATUS_CHOICES.confirmed
            subscription.save()
        return HttpResponseRedirect(self.redirect_url)

src/apps/users/views.py
from urllib.parse import urljoin

from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.views.generic import FormView
from django.views import View
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse_lazy, reverse

from apps.users.tokens import account_activation_token
from apps.users.forms import SignUpForm
from apps.users.models import User


class SignUpView(SuccessMessageMixin, FormView):

    form_class = SignUpForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:signin')
    success_message = 'User created successfully, activation email has been sent'

    def send_activation_email(self, user):
        current_site = get_current_site(self.request)
        subject = 'Activate Your MySite Account'
        uid = urlsafe_base64_encode(force_bytes(user.pk)).decode('utf-8')
        token = account_activation_token.make_token(user)
        url = urljoin(current_site.domain, reverse('users:activate', kwargs={
            'uidb64': uid,
            'token': token
        }))
        message = render_to_string('users/account_activation_email.html', {
            'user': user,
            'url': url,
        })
        user.email_user(subject, message)

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        self.send_activation_email(user)
        return super().form_valid(form)


class ActivateAccountView(View):

    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user,
                                                                     token):
            user.is_active = True
            user.save()
            login(request, user)
            messages.add_message(request, messages.INFO,
                                 _('User activated successfully'))

        else:
            messages.add_message(request, messages.INFO,
                                 _('Invalid activation link'))
        return redirect(reverse_lazy('users:signin'))


class SignInView(LoginView):

    template_name = 'users/login.html'
    success_url = reverse_lazy('users:index')

    def get_success_url(self):
        return self.success_url


class IndexView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('users:signin')
    template_name = 'dashboard/index.html'

src/templates/dashboard/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Simple Notification Server{% endblock %}</title>
    <script src="{% static 'dashboard/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'dashboard/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet"
          href="{% static 'dashboard/css/bootstrap.min.css' %}">
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
          crossorigin="anonymous">
    <script>
        $(document).ready(function () {
            $('.toast').toast('show');
        });
    </script>
    {% block  includes %}
    {% endblock %}
</head>
<body class="h-100">
{% for message in messages %}
    <div class="toast col-2 position-absolute" role="alert"
         aria-live="assertive" aria-atomic="true" data-delay="1000">
        <div class="toast-header">
            <strong class="mr-auto">{% trans 'Info' %}</strong>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast"
                    aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body">
            {{ message }}
        </div>
    </div>
{% endfor %}
<main class="h-100">
    {% block header %}
    {% endblock %}
    <div class="col-2 float-left" role="navigation">
        {% include 'dashboard/navigation.html' %}
    </div>
    {% block content %}
    {% endblock %}
</main>
</body>
</html>

src/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load i18n %}


{% block header %}
    <h1 class="display-4 mb-5">{% trans 'Personal Area' %}</h1>
{% endblock %}

src/templates/dashboard/navigation.html
{% load i18n %}
<div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
    <a class="nav-link bg-dark text-white mt-1" href="{% url 'users:index' %}" role="tab">{% trans 'Home' %}</a>
    <a class="nav-link bg-dark text-white mt-1" href="{% url 'users:index' %}" role="tab">{% trans 'Profile' %}</a>
    <a class="nav-link bg-dark text-white mt-1" href="{% url 'notifications:topic-list' %}" role="tab">{% trans 'Topics' %}</a>
    <a class="nav-link bg-dark text-white mt-1" href="{% url 'notifications:subscription-list' %}" role="tab">{% trans 'Subscriptions' %}</a>
    <a class="nav-link bg-dark text-white mt-1" href="{% url 'users:index' %}" role="tab">{% trans 'Payments' %}</a>
    <a class="nav-link bg-dark text-white mt-1" href="{% url 'users:index' %}" role="tab">{% trans 'Logout' %}</a>
</div>

src/templates/dashboard/subscription_create.html
{% extends 'dashboard/base.html' %}
{% load i18n %}

{% block header %}
     <h1 class="display-4 text-center mb-3">{% trans 'Create subscription' %}</h1>
{% endblock %}

{%  block content %}
    <div class="col-8 float-left">
         <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <p class="font-weight-bold">{{ field.label_tag }}</p>
                    {{ field }}
                </div>
             {% endfor %}
            <button class="btn btn-outline-success" type="submit">{% trans 'Create' %}</button>
        </form>
    </div>
{% endblock %}

src/templates/dashboard/subscription_delete.html
{% extends 'dashboard/base.html' %}
{% load i18n %}

{% block header %}
     <h1 class="display-4 text-center mb-3">{% trans 'Delete subscription' %}</h1>
{% endblock %}

{% block content %}
    <p>Delete <code>{{ object.endpoint }}</code>?</p>

    <form method='POST' action=''>
        {% csrf_token %}
        <p>{% trans 'Are you sure you want to delete this subscription?' %}</p>
        <input type='submit' class="btn btn-outline-danger" value='{% trans 'Yes' %}'/>
        <a href='{% url 'notifications:subscription-list' %}' class="btn btn-outline-warning">{% trans 'Cancel' %}</a>
    </form>
{% endblock %}

src/templates/dashboard/subscription_list.html
{% extends 'dashboard/index.html' %}
{% load i18n %}

{% block header %}
    <h1 class="display-4 text-center mb-3">{% trans 'Subscriptions' %}</h1>
{% endblock %}

{% block content %}
    <div class="col-10 float-right">
        {% if subscriptions %}
            <table id='subscriptions' class="table table-sm table-hover">
                <thead class="thead-dark">
                <tr>
                    <th>{% trans 'Topic' %}</th>
                    <th>{% trans 'Token' %}</th>
                    <th>{% trans 'Protocol' %}</th>
                    <th>{% trans 'Status' %}</th>
                    <th>{% trans 'Endpoint' %}</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                {% for subscription in subscriptions %}
                    <tr>
                        <td>{{ subscription.topic }}</td>
                        <td>{{ subscription.token }}</td>
                        <td>{{ subscription.protocol }}</td>
                        <td>{{ subscription.status }}</td>
                        <td>{{ subscription.endpoint }}</td>
                        <td>
                            <a href='{% url 'notifications:subscription-update' pk=subscription.id %}'
                               class="btn btn-sm btn-outline-warning">
                                <i class="far fa-edit"></i>
                            </a>
                        </td>

                        <td>
                            <a href='{% url 'notifications:subscription-remove' pk=subscription.id %}'
                               class=" btn btn-sm btn-outline-danger">
                                <i class="far fa-trash-alt"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            {% if is_paginated %}
                {% include 'includes/pagination.html' %}
            {% endif %}
        {% else %}
            <p>{% trans "No subscriptions" %}</p>
        {% endif %}
        <a href='{% url 'notifications:subscription-add' %}'
           class="btn btn-outline-success"><i
                class="fas fa-plus">&nbsp;</i>{% trans 'Add new subscription' %}
        </a>
    </div>
{% endblock %}

src/templates/dashboard/subscription_update.html
{% extends 'dashboard/base.html' %}
{% load i18n %}

{% block header %}
     <h1 class="display-4 text-center mb-3">{% trans 'Update subscription' %}</h1>
{% endblock %}


{%  block content %}
    <div class="col-8 float-left">
         <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <p class="font-weight-bold">{{ field.label_tag }}</p>
                    {{ field }}
                </div>
             {% endfor %}
            <button class="btn btn-outline-success" type="submit">{% trans 'Update' %}</button>
        </form>
    </div>
{% endblock %}

src/templates/dashboard/topic_create.html
{% extends 'dashboard/base.html' %}
{% load i18n %}

{% block header %}
    <h1 class="display-4 text-center mb-3">{% trans 'Create topic' %}</h1>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <p class="font-weight-bold">{{ field.label_tag }}</p>
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit"
                class="btn btn-outline-success">{% trans 'Create' %}</button>
    </form>
{% endblock %}

src/templates/dashboard/topic_list.html
{% extends 'dashboard/base.html' %}
{% load i18n %}

{% block header %}
    <h1 class="display-4 text-center mb-3">{% trans 'Topics' %}</h1>
{% endblock %}

{% block content %}
    <div class="col-10 float-right">
    {% if topics %}
        <table id='topics' class="table table-sm table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>{% trans 'Owner' %}</th>
                    <th>{% trans 'Title' %}</th>
                    <th>{% trans 'Edit' %}</th>
                </tr>
            </thead>
            {% for topic in topics %}
                <tr>
                    <td>{{ topic.owner }}</td>
                    <td>{{ topic.title }}</td>
                    <td>
                        <a href='{% url 'notifications:topic-update' pk=topic.id %}' class="btn btn-sm btn-outline-warning">
                            <i class="far fa-edit"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        {% if is_paginated %}
            {% include 'includes/pagination.html' %}
        {% endif %}
    {% else %}
        <p>{% trans "No topics" %}</p>
    {% endif %}
    <a href='{% url 'notifications:topic-add' %}' class="btn btn-outline-success"><i class="fas fa-plus">&nbsp;</i>{% trans 'Add new topic' %}</a>
    </div>
{% endblock %}

src/templates/dashboard/topic_update.html
{% extends 'dashboard/base.html' %}
{% load i18n %}

{% block header %}
     <h1 class="display-4 text-center mb-3">{% trans 'Update topic' %}</h1>
{% endblock %}

{%  block content %}
    <form method="post">
    {% csrf_token %}
    {% for field in form %}
                <div class="form-group">
                    <p class="font-weight-bold">{{ field.label_tag }}</p>
                    {{ field }}
                </div>
             {% endfor %}
      <button type="submit" class="btn btn-outline-success">{% trans 'Update' %}</button>
    </form>
{% endblock %}